### PR TITLE
Feature/success pages

### PR DESCRIPTION
**Pull request by katekamenieva**

### CODE REVIEW

**Comment by annie-uchiha** [comment]
The gap is getting smaller. Everything else is great!

**Review by annie-uchiha — APPROVED** [review]

**Review by annie-uchiha — APPROVED** [review]
Perfect!

**Comment by annie-uchiha** [comment]
Even got rid of my horizontal scroll on the home page. Nicely done!

**Comment by innatssss** [comment]
Great job!

**Review by innatssss — APPROVED** [review]

**Pull request merged**
