### PR TITLE
fixed width to 100vh for rectangle-black-header in main/hero-page

### PR DESCRIPTION
**Pull request by annie-uchiha**
Does this fix it for a smaller screen? This is the black rectangle under the navbar on the main/hero-page.

### CODE REVIEW

**Review by innatssss — APPROVED** [review]
Yes with reusable parts there´s no problem. Navbar and footer are perfect! But all main part still looks a bit off and gray part should be in the middle according to figma design. I think you don´t need a separate container for it. It´s just a gray background in flexbox container, and white on the sides it´s a margin left and right.

**Comment by annie-uchiha** [comment]
That's a good idea - I will try it out. Thank you!

**Comment by annie-uchiha** [comment]
With a few adjustments it worked and it is with less code. Thank you for the suggestion!

**Review by innatssss — APPROVED** [review]

**Review by tanya-rek — COMMENTED** [review]
I am not sure if it comes from this commit, but the header looks like this at my screen
Screenshot_3

**Review by tanya-rek — COMMENTED** [review]
So, actually gray area is in the center, it is cool! However, the right container with header, paragraph, and button is not horizontally center aligned. These 3 elements are wrapped with div, and you can add display: flex to this div
Screenshot_4

**Comment by annie-uchiha** [comment]
I think I will just move to my laptop to use a smaller screen size to adjust it because I fix it in a different way and to me it looks the same but seems like it gets off on normal size screens. Will redo. Thank you!

**Comment by annie-uchiha** [comment]
I think I will just move to my laptop to use a smaller screen size to adjust it because I fix it in a different way and to me it looks the same but seems like it gets off on normal size screens. Will redo. Thank you!

**Comment by annie-uchiha** [comment]
There is a flex added to the div. It is something else probably

**Comment by annie-uchiha** [comment]
It is coming from the positioning I set in the styles.css .. I used another thing for the bear and h1 tag - it should be better.  I will see what to use for the other part.

**Comment by annie-uchiha** [comment]
I added some margins and I think now it should work on your screens. It looks the same as the design and it stays in the center if I make the screen size smaller:

**Comment by annie-uchiha** [comment]
Same thing with the bear:

**Comment by annie-uchiha** [comment]
Now it responds to shrinking without getting off. Let me know if it is good.

**Review by tanya-rek — APPROVED** [review]

**Pull request merged**
