### PR TITLE
Consistency

### PR DESCRIPTION
**Pull request by innatssss**
Hey guys! I did some changes on all pages because I´ve notticed that out styles which ment to be shared and look same are not the same. Pleace check my changes and give feadback if we still have some bugs.
- Navigation bar looks different on each page (size, paddings, fonts). I picked up the design from main page and added it to every page.
- Picked up the sticky navbar from Katerina’s page and added it to others. 
- Got rid of a horizontal scroll. (Problem was with width 100vw in body section, we don’t need it).
- Footer didn’t have font style. Tania added it so I noticed that on other pages we don’t have it.
- Space between social media icons from Tania´s page (added to all others).
- Checked all links. All seem work well.

### CODE REVIEW

**Comment by annie-uchiha** [comment]
Beat me to it. Nicely done! I noticed a gap between the footer and the bottom of the page in the order now page - or is that only on my screen. I made a feature/final-styles branch that we can just delete I guess cos it is pretty much the same as this one. One more thing - did you add the animation to the paw on the menu page? Can't think of anything else.

**Comment by innatssss** [comment]
Oh sorry, I didn´t notice that branch. About the order now page can you send a screenshot becouse on my one it looks okay.
I added animation everywhere and also to the phone stick button on main page as well.
Screenshot 2024-03-22 at 11 02 32

**Comment by annie-uchiha** [comment]
order-now-gap
I think it's a margin thing

**Review by annie-uchiha — APPROVED** [review]

**Comment by annie-uchiha** [comment]
Looking great! Good job at making it consistent 👌

**Comment by katekamenieva** [comment]
@innatssss I noticed that the forms is out of the container. My screen size is 1920x1080 (windows, chrome)
image

image

**Comment by katekamenieva** [comment]
@innatssss Also, could you make the form labels the same size and remove the border from the form fields, I'd suggest making it a hover effect for these fields instead of a gray background color (it makes input text hard to read).

image

image

**Comment by innatssss** [comment]
I fixed some styles.Tell me if now it looks good. With dropdown arrow I failed I can´t add it, I´m sorry...

**Comment by katekamenieva** [comment]
@innatssss All fixed 👏  Could you consider also changing the hover effect on buttons (make background color on hover #ffffff instead of grey) This way contrast will be higher, it's better for accessibility and just easier on the eyes 😅 

Don't worry about the drop-down icon, it's okay

**Review by katekamenieva — APPROVED** [review]

**Pull request merged**
